import Footer from "@/components/Footer";
import { Navbar } from "@/components/Navbar";
import ContextProvider from "@/context/ContextProvider";
import type { Metadata } from "next";
import { Griffy, Quicksand } from "next/font/google";
import "./globals.css";

const griffy = Griffy({
  subsets: ["latin"],
  weight: ["400"],
});

const quickSand = Quicksand({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Matheus Senas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${griffy.className} antialiased`}>
        <Navbar />
        <ContextProvider>{children}</ContextProvider>
        <Footer />
      </body>
    </html>
  );
}
